swagger: "2.0"

info:
  version: "1.0.0"
  title: 商品API
  description: 商品相关，只有个搜索商品的

basePath: "/goods_search"

paths:
  /query:
    get:
      operationId: routes.goods.api_goods_query
      tags:
        - 搜索
      summary: 搜索 - todo没有分页
      description: 搜索商品
      parameters:
        - $ref: '#/parameters/user_jwt'
        - name: key
          in: query
          description: "关键词"
          default: apple
          required: true
          type: string
      responses:
        "200":
          description: |
            搜索商品 
            code data msg 是固定格式  
            在这个api中，data类型是list[dict]，dict中是业务需要的参数，详细解释如下
            
            | key      | 类型 | 含义        |
            | ---- | ---- | ---- |
            | sku_id     | int    | sku_id |
            | title     | string    | title |
            | description     | string    | description |
            
            例子
            ```
            {
              "code": 200,
              "data": [
                {
                  "sku_id": 5,
                  "title": "new apple",
                  "description": "this is a new apple"
                }
              ],
              "msg": "ok"
            }
            ```

  /recommend:
    get:
      operationId: routes.goods.api_goods_recommend
      tags:
        - 推荐
      summary: 推荐 - todo没有分页
      description: 推荐商品，需要前端根据实际情况，异步请求或者搜索不到的时候请求
      parameters:
        - $ref: '#/parameters/user_jwt'
      responses:
        "200":
          description: 和 /query 的搜索接口返回一模一样

  /update:
    post:
      operationId: routes.goods.api_goods_update
      tags:
        - 更新
      summary: 更新
      description: 更新商品, 参数 sku_id 在数据库有就更新，没有就创建。这个api不是题目要求的，做这个是展示异步更新的逻辑
      parameters:
        - $ref: '#/parameters/user_jwt'
        - name: post_goods_update_para
          in: body
          required: true
          schema:
            $ref: '#/definitions/post_goods_update_data'
      responses:
        "200":
          description: ok


parameters:
  user_jwt:
    name: GoodsSearch-Token
    in: header
    required: true
    type: string
    default: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjQ4MjEzMzAyMTcsImN0IjoxNjk5MjY2MjE3fQ.mbTwkLMmORM1atKUkgMsIzpecdsgeTAb-B0-p5XGT6w
    description: 登录态 jwt token，在这个例子中，这里先写死。


definitions:
  post_goods_update_data:
    type: object
    properties:
      sku_id:
        type: integer
        description: sku id, 数据库有就更新，没有就创建
      title:
        type: string
        description: title
      description:
        type: string
        description: description

    required:
      - sku_id
      - title
      - description
